version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: database-assignment4-db-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: subscribers
      MYSQL_USER: subuser
      MYSQL_PASSWORD: subpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 