- name: Tear down MySQL container
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Stop and remove MySQL container
      shell: |
        docker rm -f flyway-mysql || echo "MySQL container not found or already removed"
