---
- name: Setup MySQL environment and run initial migrations
  hosts: localhost
  connection: local
  tasks:
    - name: Start MySQL container
      community.docker.docker_container:
        name: database-assignment4-db-1
        image: mysql:5.7
        state: started
        restart_policy: unless-stopped
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: subscribers
          MYSQL_USER: subuser
          MYSQL_PASSWORD: subpass
        published_ports:
          - "3306:3306"

    - name: Run initial Flyway migrations using docker
      shell: |
        docker run --rm \
          --network container:database-assignment4-db-1 \
          -v {{ playbook_dir }}/sql:/flyway/sql \
          -v {{ playbook_dir }}/flyway.conf:/flyway/conf/flyway.conf \
          flyway/flyway migrate
