name: Flyway Migrations Demo

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  flyway-demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start MySQL container
      run: |
        docker run -d \
          --name mysql-demo \
          -e MYSQL_ROOT_PASSWORD=root123 \
          -e MYSQL_DATABASE=subscribers_db \
          -p 3306:3306 \
          mysql:8.0

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        timeout 120 bash -c 'until docker exec mysql-demo mysqladmin ping -h localhost -u root --silent; do echo "Waiting..."; sleep 2; done'
        echo "MySQL is ready!"

    - name: Debug MySQL container
      run: |
        echo "Checking MySQL container status:"
        docker ps
        echo "Checking MySQL logs:"
        docker logs mysql-demo
        echo "Testing MySQL connection with root (no password):"
        docker exec mysql-demo mysql -u root -e "SELECT 'Root connection successful' as status;"
        echo "Checking available databases:"
        docker exec mysql-demo mysql -u root -e "SHOW DATABASES;"

    - name: List available migration files
      run: |
        echo "Available migration files:"
        ls -la migrations/init/
        ls -la migrations/incremental/
        ls -la sql/

    - name: Create database if not exists
      run: |
        echo "Creating database if not exists..."
        docker exec mysql-demo mysql -u root -e "CREATE DATABASE IF NOT EXISTS subscribers_db;"
        echo "Database created successfully!"

    - name: Run migrations manually
      run: |
        echo "Running migrations manually..."
        echo "Creating subscriber table..."
        docker exec mysql-demo mysql -u root subscribers_db -e "CREATE TABLE IF NOT EXISTS subscriber (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE);"
        echo "Adding name column..."
        docker exec mysql-demo mysql -u root subscribers_db -e "ALTER TABLE subscriber ADD COLUMN IF NOT EXISTS name VARCHAR(255);"
        echo "Migrations completed!"

    - name: Verify migration
      run: |
        echo "Verifying migration..."
        docker exec mysql-demo mysql -u root subscribers_db -e "SHOW TABLES;"
        docker exec mysql-demo mysql -u root subscribers_db -e "DESCRIBE subscriber;"

    - name: Cleanup
      if: always()
      run: |
        docker stop mysql-demo || true
        docker rm mysql-demo || true
