name: Flyway Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker (if needed)
        uses: docker/setup-buildx-action@v2

      - name: Run initial migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/sql:/flyway/sql \
            -v ${{ github.workspace }}/flyway.conf:/flyway/conf/flyway.conf \
            flyway/flyway migrate

      - name: Run incremental migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/migrations_incremental:/flyway/sql \
            -v ${{ github.workspace }}/flyway.conf:/flyway/conf/flyway.conf \
            flyway/flyway migrate

      - name: Deployment complete message
        run: echo "Flyway migrations completed successfully!"
