- name: Run Flyway migrations using Docker
  run: |
    docker run --rm \
      -v ${{ github.workspace }}/sql:/flyway/sql \
      flyway/flyway:10 \
      -url=jdbc:mysql://localhost:3306/$DB_NAME \
      -user=$DB_USER \
      -password=$DB_PASSWORD \
      migrate
  env:
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: subscribers_db
