name: Flyway Database Migrations

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start MySQL container
      run: |
        docker run -d \
          --name database-assignment4-db-1 \
          -e MYSQL_ROOT_PASSWORD=root123 \
          -e MYSQL_DATABASE=subscribers \
          -p 3306:3306 \
          mysql:8.0

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        timeout 120 bash -c 'until docker exec database-assignment4-db-1 mysqladmin ping -h localhost -u root --silent; do echo "Waiting..."; sleep 2; done'
        echo "MySQL is ready!"

    - name: Debug MySQL container
      run: |
        echo "Checking MySQL container status:"
        docker ps
        echo "Checking MySQL logs:"
        docker logs database-assignment4-db-1
        echo "Testing MySQL connection with root (no password):"
        docker exec database-assignment4-db-1 mysql -u root -e "SELECT 'Root connection successful' as status;"
        echo "Checking available databases:"
        docker exec database-assignment4-db-1 mysql -u root -e "SHOW DATABASES;"

    - name: Debug migration files
      run: |
        echo "Current directory:"
        pwd
        echo "Listing migration files:"
        ls -la migrations/init/
        ls -la migrations/incremental/

    - name: Run Initial Flyway Migrations
      run: |
        echo "Running initial migrations..."
        docker run --rm \
          --network host \
          -v "${{ github.workspace }}/migrations/init:/flyway/sql" \
          flyway/flyway:9-alpine \
          -url=jdbc:mysql://localhost:3306/subscribers?allowPublicKeyRetrieval=true&useSSL=false \
          -user root \
          migrate

    - name: Run Incremental Flyway Migrations
      run: |
        echo "Running incremental migrations..."
        docker run --rm \
          --network host \
          -v "${{ github.workspace }}/migrations/incremental:/flyway/sql" \
          flyway/flyway:9-alpine \
          -url=jdbc:mysql://localhost:3306/subscribers?allowPublicKeyRetrieval=true&useSSL=false \
          -user root \
          migrate

    - name: Verify migrations
      run: |
        echo "Verifying migrations..."
        docker exec database-assignment4-db-1 mysql -u root subscribers -e "SHOW TABLES;"

    - name: Run Database Tests
      run: |
        pip install mysql-connector-python
        python test_subscribers.py

    - name: Deployment Complete
      run: |
        echo "✅ Database deployment completed successfully!"
        echo "📊 Initial migrations: Applied"
        echo "🔄 Incremental migrations: Applied"
        echo "🧪 Tests: Passed"

    - name: Cleanup
      if: always()
      run: |
        docker stop database-assignment4-db-1 || true
        docker rm database-assignment4-db-1 || true
