<<<<<<< HEAD
name: Flyway Database Migrations

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start MySQL container
      run: |
        docker run -d \
          --name database-assignment4-db-1 \
          -e MYSQL_ROOT_PASSWORD=rootpass \
          -e MYSQL_DATABASE=subscribers \
          -e MYSQL_USER=subuser \
          -e MYSQL_PASSWORD=subpass \
          -p 3306:3306 \
          mysql:8.0

    - name: Wait for MySQL to be ready
      run: |
        timeout 60 bash -c 'until docker exec database-assignment4-db-1 mysqladmin ping -h localhost -u root -prootpass --silent; do sleep 1; done'

    - name: Run Initial Flyway Migrations
      run: |
        docker run --rm \
          --network container:database-assignment4-db-1 \
          -v ${{ github.workspace }}/migrations/init:/flyway/sql \
          -v ${{ github.workspace }}/flyway.conf:/flyway/conf/flyway.conf \
          flyway/flyway:9-alpine migrate

    - name: Run Incremental Flyway Migrations
      run: |
        docker run --rm \
          --network container:database-assignment4-db-1 \
          -v ${{ github.workspace }}/migrations/incremental:/flyway/sql \
          -v ${{ github.workspace }}/flyway_incremental.conf:/flyway/conf/flyway.conf \
          flyway/flyway:9-alpine migrate

    - name: Run Database Tests
      run: |
        pip install mysql-connector-python
        python test_subscribers.py

    - name: Deployment Complete
      run: |
        echo "✅ Database deployment completed successfully!"
        echo "📊 Initial migrations: Applied"
        echo "🔄 Incremental migrations: Applied"
        echo "🧪 Tests: Passed"

    - name: Cleanup
      if: always()
      run: |
        docker stop database-assignment4-db-1 || true
        docker rm database-assignment4-db-1 || true
=======
name: Flyway Migration

on:
  push:
    branches:
      - main

jobs:
  flyway:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: subscribers
          MYSQL_USER: subuser
          MYSQL_PASSWORD: subpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Wait for MySQL to be healthy
        run: sleep 30

      - name: Install Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.2/flyway-commandline-9.22.2-linux-x64.tar.gz | tar xz
          sudo mv flyway-*/flyway /usr/local/bin/

      - name: Run initial migration
        run: flyway -configFiles=flyway.conf migrate

      - name: Run incremental migration
        run: flyway -configFiles=flyway_incremental.conf migrate

      - name: ✅ Deployment complete
        run: echo "✅ Flyway migration completed successfully"
>>>>>>> f7444b639cdd3cfdaccd957c0f01d62b7dce86e0
