name: Flyway Migrations Demo

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  flyway-demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start MySQL container
      run: |
        docker run -d \
          --name mysql-demo \
          -e MYSQL_ROOT_PASSWORD=root \
          -e MYSQL_DATABASE=subscribers_db \
          -p 3306:3306 \
          mysql:8.0

    - name: Wait for MySQL to be ready
      run: |
        timeout 60 bash -c 'until docker exec mysql-demo mysqladmin ping -h localhost -u root -proot --silent; do sleep 1; done'

    - name: Test MySQL connection
      run: |
        docker exec mysql-demo mysql -u root -proot -e "SELECT 1;"

    - name: List available migration files
      run: |
        echo "Available migration files:"
        ls -la migrations/init/
        ls -la migrations/incremental/
        ls -la sql/

    - name: Run Flyway migrations using Docker
      run: |
        docker run --rm \
          --network container:mysql-demo \
          -v "${{ github.workspace }}/migrations/init:/flyway/sql" \
          -v "${{ github.workspace }}/flyway_demo.conf:/flyway/conf/flyway.conf" \
          flyway/flyway:9-alpine \
          migrate

    - name: Verify migration
      run: |
        docker exec mysql-demo mysql -u root -proot subscribers_db -e "SHOW TABLES;"

    - name: Cleanup
      if: always()
      run: |
        docker stop mysql-demo || true
        docker rm mysql-demo || true
