name: Flyway Migration

on:
  push:
    branches:
      - main

jobs:
  flyway:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: subscribers
          MYSQL_USER: subuser
          MYSQL_PASSWORD: subpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Wait for MySQL to be healthy
        run: sleep 30

      - name: Install Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.2/flyway-commandline-9.22.2-linux-x64.tar.gz | tar xz
          sudo mv flyway-*/flyway /usr/local/bin/

      - name: Run initial migration
        run: flyway -configFiles=flyway.conf migrate

      - name: Run incremental migration
        run: flyway -configFiles=flyway_incremental.conf migrate

      - name: ✅ Deployment complete
        run: echo "✅ Flyway migration completed successfully"
